### ISSUE TITLE
Dialog message before short break

### ISSUE THREAD

**Issue by agile-user** [gfreeau/cinnamon-pomodoro#25]
Please put back dialog message beforre short break and an option to activate it in settings.

**Comment by cwilli34** [comment]
I would like this too.  I don't even get a notification in Cinnamon for short breaks, so I never even notice when I am supposed to have a short break and work right on through it.  Nothing notifies me.

**Comment by DavidWiesner** [comment]
To add another dialog on the short break will be very helpful. So you can e.g. manual start the next prodomo  in contrast to automatically start the next prodomo after short break finished.

**Comment by gfreeau** [comment]
Resolved in https://github.com/gfreeau/cinnamon-pomodoro/pull/59
