### ISSUE TITLE
Feature request: different color tomato for break timer

### ISSUE THREAD

**Issue by isomerase** [gfreeau/cinnamon-pomodoro#32]
If I pause the app, go afk and return, I can't tell at a glance whether the timer is for work or break. I've seen other pomodoro apps change the color of the tomato to distinguish the break timer.

**Comment by MateuszG** [comment]
+1

**Comment by isaeff** [comment]
+1

**Comment by kunnix** [comment]
Pull request implementing this: #62

You can test it here: https://github.com/kunnix/cinnamon-pomodoro/
