### ISSUE TITLE
Definition of pomodoro

### ISSUE THREAD

**Issue by galou** [gfreeau/cinnamon-pomodoro#34]
According to http://en.wikipedia.org/wiki/Pomodoro_Technique, a pomodoro is a 25-min time interval. Here, it is a set of 4 times 25-min intervals that is considered a pomodoro.
I think the applet should be consistent with the original definition.

**Comment by gfreeau** [comment]
You can change the setup to suit this preference. In the options, change number of pomodori from 4 to 1.

By default, the applet uses the setup described on that wikipedia page under the heading "Underlying principles".

**Comment by gfreeau** [comment]
@galou, can you update the applet to have consistent naming for pomodoro, pomodori.

I don't mind if we settle on pomodoro, as long as it is consistent everywhere.

With your new changes we are mixing terms.
