### ISSUE TITLE
Pomodoro (or play command) keeps running when Cinammon closes

### ISSUE THREAD

**Issue by MiguelMCarrillo** [gfreeau/cinnamon-pomodoro#37]
If you start pomodoro and check 'Play Timer Sound' in its configuration so you can hear it running and then log-out you will be able to keep hearing the ticking sound. If you go to a console (ctrl-alt-f1) and log in you will also hear it ticking. I read the code and I see (and tested) that if Cinnamon is restarted the play command is killed. However, this does not seems to happen if you just log out.

**Comment by MavropaliasG** [comment]
True. also if I have a pomodoro active and I even remove the applet from cinnamon, it continues to run in the background, and can have multiple instances.
