### ISSUE TITLE
Autostart timer after starting pomodoro app [Option]

### ISSUE THREAD

**Issue by MateuszG** [gfreeau/cinnamon-pomodoro#40]
This is GREAT app, but I often forget to turn in ON.
### What is need:
- Add option in preferences to auto start timer on run

> Please add this feature!

**Comment by MateuszG** [comment]
At the end of init method, after line: https://github.com/gfreeau/cinnamon-pomodoro/blob/master/pomodoro%40gregfreeman.org/applet.js#L105

Need to call:
```
this._timerQueue.start();
```

**Comment by gfreeau** [comment]
Feel free to submit a pull request.

**Comment by laex333** [comment]
+1
