### ISSUE TITLE
Interface options do not work

### ISSUE THREAD

**Issue by klmitch** [gfreeau/cinnamon-pomodoro#42]
I have the "Show Dialog Messages" option turned on, and I have the "Auto start a new pomodoro after a break ends" option turned off; however, these options appear to have no effect.  After one Pomodoro, instead of getting a dialog, I just get a notification stating, "Take a short break!"  Additionally, as soon as the short break timer ends, a new Pomodoro begins counting down immediately.

It appears I can get the dialog behavior I want by changing the setting, "Number of pomodori before long break," to the value 1, but that of course means I only get a single break length—whatever I set the "Long Break Duration" to.

**Comment by gfreeau** [comment]
Which version of cinnamon are you using? Which version of the this applet?

**Comment by klmitch** [comment]
cinnamon-2.6.7, most recent version of the app—at least, it's not showing as upgradeable after refreshing the app list.

**Comment by gfreeau** [comment]
The dialog window shows up at the end of the pomodoro (long break). The pomodoro is made up of 4 pomodori, at the end of each pomodori you get the notification instead of the dialog. (short break).

The applet is working as designed instead of a bug.

**Comment by klmitch** [comment]
I see.  I would actually prefer a dialog at the end of each of the pomodori.  I would also prefer that the next pomodori not begin until I specifically request it…
