### ISSUE TITLE
No sound and notifications when a pomodori ends or starts

### ISSUE THREAD

**Issue by aldeano** [gfreeau/cinnamon-pomodoro#43]
I got configured two sounds for breaks between pomodoris, and they don't play
![captura de pantalla de 2015-09-19 15-51-06](https://cloud.githubusercontent.com/assets/622453/9977637/433337d6-5ee5-11e5-9b2c-00ff4bfae6ba.png)

Also the applet doesn't show notifications when a break starts or ends.

**Comment by romseguy** [comment]
This isn't a solution to your issue but here's an [alternative](https://github.com/romseguy/cinnamon-pomodoro). Although it features the bare minimum according to my needs, I made sure to keep the code as simple as possible if you want to adjust it to your needs.

**Comment by isaeff** [comment]
+1
I have the same problem

**Comment by gfreeau** [comment]
@aldeano I can confirm your issue but I was able to make the sound change by restarting cinnamon after changing the tick sound.

`Alt` + `F2`, press `r` key and then enter.

**Comment by Farkal** [comment]
I also need to display some sound when pomodoro session start or end (because i meditate on each pause so i close my eyes and don't look at the timer)
Thanks a lot for this applet.

**Comment by m-antis** [comment]
Ditto

**Comment by Farkal** [comment]
You can just add this code inside _applet.js_ if you want the break sound at the beginning of new session: (i add it at line 324)

```
pomodoroTimer.connect('timer-started', Lang.bind(this, function() {
            this._playBreakSound();
        }));
```

**Comment by gfreeau** [comment]
@Farkal Are you able to do a pull request and add an option such as "Play Break Finished Sound"?

**Comment by Farkal** [comment]
I have added the possibility to select the sound to play in the settings.

**Comment by gfreeau** [comment]
Thank you
