### ISSUE TITLE
Feature request: Hide ticking time

### ISSUE THREAD

**Issue by snaumov** [gfreeau/cinnamon-pomodoro#47]
It would be great to have an option to hide the time left in current pomodoro, because I'm usually distracted by this ticking numbers on panel. Also, I don't want to know basically how much time is left. Thank you!

**Comment by gfreeau** [comment]
Good idea, a pull request is welcome.

**Comment by ncelerier** [comment]
I think I should be able to do this one. I'm having a look ...

**Comment by ncelerier** [comment]
Since PR for this feature has been merged, I think you can close this issue ?

**Comment by gfreeau** [comment]
@snaumov this will be released into cinnamon spices within the next day. Thank you @ncelerier .

**Comment by ncelerier** [comment]
I'll quickly update the french translation then.
