### ISSUE TITLE
Changing timer sound file doesn't work

### ISSUE THREAD

**Issue by ThomasProctor** [gfreeau/cinnamon-pomodoro#49]
The settings give an option to change the timer sound, however it still plays tick.ogg if you change it.

**Comment by gfreeau** [comment]
There is a change in newer versions of cinnamon where the changes to settings don't take effect without a cinnamon restart.

A change needs to be made to this code, for now just restart cinnamon uses Alt-F2 and then press the `r` key.

**Comment by gfreeau** [comment]
Pull requests are welcome.

**Comment by kunnix** [comment]
What I've seen is that the ticker sound would not be changed until the timers are reset.

This PR should fix it: https://github.com/gfreeau/cinnamon-pomodoro/pull/64

You can test it here: https://github.com/kunnix/cinnamon-pomodoro/
