### ISSUE TITLE
State of the branches and released version

### ISSUE THREAD

**Issue by ncelerier** [gfreeau/cinnamon-pomodoro#55]
Hello, 

I wonder if we need to keep the dev branch. The dev branch seems to be dead. The master branch is ahead of it and more active. Also the master branch seems to contains all the commits from dev. 

Also, the master branch is ahead of what is of the official page of the applet: https://cinnamon-spices.linuxmint.com/applets/view/131. Shouldn't the master branch be the same as the "production" version ? 

Thank you.

**Comment by gfreeau** [comment]
Hello,

Thank you for your pull requests. I will update the release on cinnamon spices.

The dev branch is no longer needed and has been removed. It just had some scripts to create the zip package.

**Comment by ncelerier** [comment]
You are welcome. Ok for the branches and the release ! Thanks.
