### ISSUE TITLE
Add Setting to change the volume of the notification sounds

### ISSUE THREAD

**Issue by DavidWiesner** [gfreeau/cinnamon-pomodoro#56]
Please add an option to change the volume of the notification sounds.

**Comment by gfreeau** [comment]
We use SoX play. The command line tool takes a `--volume` option to control the sounds so this should be easy.

Pull requests are welcome. You just need to add the applet option and then modify `sound.js`.

```js
let command = "play -q '%s'".format(this._soundPath);
```

**Comment by kunnix** [comment]
Pull request implementing this: https://github.com/gfreeau/cinnamon-pomodoro/pull/64

You can test it here: https://github.com/kunnix/cinnamon-pomodoro/

**Comment by gfreeau** [comment]
Fixed by @kunnix . Thank you
