### ISSUE TITLE
add blocking dialog for pomodoro end

### ISSUE THREAD

**Issue by antoine-gallix** [gfreeau/cinnamon-pomodoro#68]
Working in an open space, I work without sound. The end of a pomodoro is only notified by a bell sound, or a small notification on my secondary screen (small notebook on the side of my main working screen, but primary in cinnamon). The notification or blocking screen appears only after the pause is finished, or after all pomodori in a set are finished. As a result, I often miss the end of the pomodoro. It would be nice to also have a blocking dialog for the end of a pomodoro, so every event (pomodoro ends, short pause ends, set ends, long pause ends) would appear as a screen blocking dialog, if dialog are enabled in settings.

**Comment by AHolliday** [comment]
I would really like this feature too!

**Comment by laex333** [comment]
+1

**Comment by gfreeau** [comment]
It's been a long time but I've added this feature and a new option to toggle it on in this commit: https://github.com/gfreeau/cinnamon-pomodoro/commit/a967661aa6fbb7db77a6554d51bcae55a8f47e87 I will update the applet in cinnamon spices shortly but you can test it earlier using repo and running update-applet.sh.
