### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by klmitch** [gfreeau/cinnamon-pomodoro#69]
Fedora 25.  I haven't started using pomodoro again until recently, but it seems I can't get it to play any sounds at all.  "play" command is installed and in the PATH, and the included sound files are properly configured and I've confirm that "play" is able to play them.  I've even tried uninstalling and reinstalling the applet (pulling it in from Cinnamon's applet downloader).  Any ideas?

**Comment by blodstone** [comment]
+1 Archlinux, having the same problem also.

**Comment by gfreeau** [comment]
The code that plays sound is here: https://github.com/gfreeau/cinnamon-pomodoro/blob/master/pomodoro%40gregfreeman.org/sound.js

Here is my recommendations to test:

1. Run this command:

```
play --volume 0.1 -q ~/.local/share/cinnamon/applets/pomodoro@gregfreeman.org/sounds/tick.ogg repeat 9999
```

To confirm play is installed and will play the sound, you indicated you did this already.

2. Check the path to play

```
which play
```

Now I would hard code this value into `sound.js` to confirm there is no path issues, For example, change this code

```
let command = "play";
```

to 

```
let command = "/usr/bin/play";
```
Substitute this for your path. Now reload cinnamon with `alt+f2 r`. You can also use `testdeploy.sh` in this repository for deploying a test version.

Before we debug further, see if this works.

**Comment by klmitch** [comment]
1. Yes, that works; I hear a ticking sound.
2. I hard-coded "/usr/bin/play" (my path to the "play" binary) in the applet as directed, then reloaded cinnamon, turned on ticking in the pomodoro settings, and started a pomodoro—no sound.  I waited all the way through a 25 minute cycle, and heard no sound at the end, either.

**Comment by gfreeau** [comment]
@klmitch There is a function in applet.js that I use when developing so that I don't have to wait a long time to get feedback, here it is:

```
// this function is useful for development of the applet
// as we can quickly disable long running settings for quick tuning
// i.e a setting of 25 in the options can mean 25 seconds if we comment out the '* 60'
// makes it easy to test all of the timers quickly
function convertMinutesToSeconds(minutes) {
    return minutes * 60;
}
```

When developing, I don't multiply by 60 and just return the minutes value, this means I can get through pomodoro in 25 seconds instead of minutes.

What version of cinnamon are you running in fedora 25?

**Comment by gfreeau** [comment]
@klmitch 

I just installed Fedora 25 in a VM and followed these steps:

1. Install sox play with `dnf install sox`
2. Install pomodoro applet
3. Enable the tick sound, go into settings and click the checkbox `Play Timer Sound` which is disabled by default.

I am able to get the sounds playing. I installed Fedora 25 from https://muug.ca/mirror/fedora/linux/releases/25/Spins/x86_64/iso/Fedora-Cinnamon-Live-x86_64-25-1.3.iso

**Comment by klmitch** [comment]
* cinnamon-3.4.6-15.fc25.x86_64
* sox-14.4.2.0-6.fc24.x86_64
* Pomodoro timer from 2017-06-07 05:00:06 UTC

It's not the tick sound I actually want, btw; I actually find the ticking distracting.  I'm just using that as an indicator of the problems with sound.

The only other thing I can think to mention is that I installed sox _after_ I installed pomodoro in the window manager; however, IIRC, in my efforts to debug on my side, I tried uninstalling it and re-installing it.  Also, I've had FC25 on this system for a while, so I've taken all the Fedora updates and rebooted several times…

**Comment by gfreeau** [comment]
I have confirmed this behaviour in cinnamon 3.4. Seems to only affect newer versions.

**Comment by klmitch** [comment]
I just updated to Fedora 26 with cinnamon 3.6 and am still seeing the same behavior.  Any ETA on a fix?  I'm having to consider using phone apps to get around the lack of sound.

**Comment by gfreeau** [comment]
I can't reproduce it.

Someone will need to be able to reproduce it in a virtual machine or similar and do the ground work.

**Comment by klmitch** [comment]
I thought you had reproduced it?  You commented on September 19th that you had "confirmed this behavior in cinnamon 3.4".  It happens for me in Fedora 26 on my personal laptop, and in Fedora 25 in a VM running on my work laptop…

**Comment by gfreeau** [comment]
You can try the latest master branch including this commit: https://github.com/gfreeau/cinnamon-pomodoro/commit/682810df603e4dd5fbac75f854532dfcd066f46e

This was the bug I was referring to above. If this does not fix your problem, then the no sound bug has not been reproduced.

**Comment by klmitch** [comment]
I just caught sight of the email where you commented on this bug back in November, so sorry for the delay in response.  I did just try the specific change you referenced, and that restores sound functionality to the Pomodoro timer for me.  Do you have any timeframe for when this change will hit the Cinnamon applet repository?

**Comment by photong** [comment]
I can confirm that sound does not work on Linux Mint 19. Installing sox allows the default "ticker" sound to play, but custom sound files (tried .wav and .ogg) for "break" and "start" are never played. As mentioned above, this severely cripples the utility of this applet.

**Comment by gfreeau** [comment]
I added a pull request to main the repo here: https://github.com/linuxmint/cinnamon-spices-applets/pull/1969
