### ISSUE TITLE
 Keyboard shortcuts

### ISSUE THREAD

**Issue by nurgasemetey** [gfreeau/cinnamon-pomodoro#72]
Hello,

Thank you for this awesome applet for my productivity boost. 

I just wanted to know if it possible to add keyboard shortcuts to this applet? Does cinnamon support this? If it supports, I can code and make pull request.

**Comment by areographe** [comment]
Hey, I know this was a while ago but I'd be interested in this feature too. I use the Cinnamon Weather applet and it has the capacity to set a keybinding for clicking the applet:

https://github.com/linuxmint/cinnamon-spices-applets/blob/1297f0bb6e2a27e0cf489459dfc1bf525a4174c2/weather%40mockturtl/files/weather%40mockturtl/applet.js#L359

Looks like it is possible. I haven't worked on any applets before but happy to help @nurgasemetey if you wanted to try to implement this.

**Comment by gfreeau** [comment]
I added hotkey support to open the applet menu here: https://github.com/gfreeau/cinnamon-pomodoro/commit/5d5fbe118c7c9cfbdcebf84eb30b6df9baf9bf0c. I will add it to the main spices repo soon.
