### ISSUE TITLE
does not work on Linux Mint 20

### ISSUE THREAD

**Issue by badpenguin** [gfreeau/cinnamon-pomodoro#75]
It seems that the applet requires /usr/bin/python or a "python" binary into the path.
In Linux Mint 20 there is not such thing
and the applet.js crashes.

The python binary seems completely unnecessary to me: i wonder why a plain shell script isn't used.

**Comment by kunnix** [comment]
Not sure if provided by Mint, but first line on https://github.com/gfreeau/cinnamon-pomodoro/blob/master/pomodoro%40gregfreeman.org/bin/kill-looping-sound.py can probably be replaced by `#!/usr/bin/env python` or `#!/usr/bin/env python2`

**Comment by badpenguin** [comment]
> Not sure if provided by Mint, but first line on https://github.com/gfreeau/cinnamon-pomodoro/blob/master/pomodoro%40gregfreeman.org/bin/kill-looping-sound.py can probably be replaced by `#!/usr/bin/env python` or `#!/usr/bin/env python2` (as a quick fix)

this does not fix the problem because the script is called from applet.js through the "python" binary :-)

**Comment by gfreeau** [comment]
@badpenguin As a quick fix you can try making a symlink for `/usr/bin/python` pointing to either python2 or python3? (make sure python is installed)

A proper fix is needed and you're right a bash script could do the job as well. It's been awhile since I worked on this but I remember using python for easier escaping of the arguments.

If you write a bash script, happy to use it.

**Comment by badpenguin** [comment]
> If you write a bash script, happy to use it.

I can help, but I need to know what the script is exactly doing:

```
command = "ps aux | grep 'play -q' | grep %s | awk '{print $2}' | xargs -r kill -9" % (quote(argv[1]))
```

what is the purpose of "grep %s" for ? %s is the name of the sound file?

**Comment by gfreeau** [comment]
Yes, it's the path to the tick sound, it searches for any processes that include it and then kills them to stop the sound.

**Comment by gfreeau** [comment]
Fixed in https://github.com/gfreeau/cinnamon-pomodoro/commit/8052703b5858c45b06a5eee991bb871aeecdd282

Defaults to Python3 which is default from Mint 18 onwards.
